### ISSUE TITLE
NoClassDefFoundError: android.icu.text.SimpleDateFormat

### ISSUE THREAD

**Issue by MatnazaroFF** [SumSubstance/idensic-mobile-sdk-sample-android#10]
SDK version: 1.19.7

Stack trace:
```
Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/icu/text/SimpleDateFormat;
       at com.sumsub.sns.core.common.KibanaLogger.<init>(KibanaLogger.java:27)
       at com.sumsub.sns.domain.PrepareSDKUseCase.run(PrepareSDKUseCase.java:99)
       at com.sumsub.sns.domain.PrepareSDKUseCase$run$1.invokeSuspend(PrepareSDKUseCase.java)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:106)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5912)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
```

<img width="452" alt="Screen Shot 2022-10-24 at 17 14 22" src="https://user-images.githubusercontent.com/18504406/197523318-fab61b42-cb80-491d-b0c0-510cb68288a0.png">

SimpleDateFormat (added in API level 24)
https://developer.android.com/reference/android/icu/text/SimpleDateFormat

**Comment by palmut** [comment]
Thank you! This issue was fixed in 1.20.0
